cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # Новые маршруты для увеличения и уменьшения количества
    path('increment/<int:product_id>/', views.cart_increment, name='cart_increment'),
    path('decrement/<int:product_id>/', views.cart_decrement, name='cart_decrement'),
]
 

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

store/urls.py
from django.urls  import path
from . import views

app_name = 'store' #Пространство имен

urlpatterns = [
    path('',views.home, name='home'),
    path('product/<slug:product_slug>/',views.product_detail, name='product_detail'),
    path('categories/',views.category_list,name='category_list'),
    path('category/<slug:category_slug>/',views.product_list_by_category,name='product_list_by_category'),
]

techstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls',namespace='store')),
    path('cart/', include('cart.urls',namespace='cart')),
    path('orders/', include('orders.urls',namespace='orders')),
]

# Это нужно только в режиме разработки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.urls import reverse 

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255,unique=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=255, unique=True, help_text='Используется для URL, например "videokarty"')
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True, verbose_name='Изображение категории')

    class Meta:
        # Настройки для отображения в админ-панели
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products',verbose_name='Категория')
    name = models.CharField(max_length=255,unique=True, verbose_name='Название товара')
    slug = models.SlugField(max_length=255, unique=True, help_text='Используется для URL, например "videokarty"')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Изображение')
    stock = models.PositiveIntegerField(verbose_name='Количество на складе', )
    is_available = models.BooleanField(default=True,verbose_name='Доступен для продажи')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления ')

    class Meta:
        # Настройки для отображения в админ-панели
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

cart/forms.py
from django import forms

# Создаем список для выбора количества товара от 1 до 20.
# Это более явный способ сделать то же самое, что и генератор списка.
PRODUCT_QUANTITY_CHOICES = []
for i in range(1, 21):
    PRODUCT_QUANTITY_CHOICES.append((i, str(i)))


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label='Количество'
    )
    # Поле, которое говорит, нужно ли перезаписать количество или добавить к существующему
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

# Новое представление для увеличения количества
@require_POST
def cart_increment(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')

# Новое представление для уменьшения количества
@require_POST
def cart_decrement(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    
    # Получаем товар из сессии, чтобы проверить его количество
    item = cart.cart.get(str(product_id))

    if item:
        if item['quantity'] > 1:
            # Уменьшаем количество на 1
            cart.add(product=product, quantity=-1, update_quantity=False)
        else:
            # Если товар один, удаляем его
            cart.remove(product)
            
    return redirect('cart:cart_detail')

# Обновленное представление для страницы корзины
def cart_detail(request):
    cart = Cart(request)
    # Удаляем создание формы, она больше не нужна здесь
    return render(request, 'cart/detail.html', {'cart': cart})

 

orders/views.py
from django.shortcuts import render

# Create your views here.

store/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from django.db.models import Count,Q
from cart.forms import CartAddProductForm

# Create your views here.
def home(request):
    products = Product.objects.filter(is_available=True)[:8]
    context = {'products':products}
    return render(request,'index.html',context)


def product_detail(request, product_slug):
    # get_object_or_404 либо находит объект , либо возвращает ошибку 404
    product = get_object_or_404(Product, slug = product_slug, is_available =True)
    cart_product_form = CartAddProductForm()
    context = {'product': product,'cart_product_form': cart_product_form}
    return render(request,'product_detail.html',context)

def category_list(request):
    categories = Category.objects.annotate(
        product_count = Count('products',filter=Q(products__is_available=True))
    ).order_by('-product_count','name')
    context = {'categories':categories}
    return render(request,'store/category_list.html',context)

def product_list_by_category(request,category_slug):
    category = get_object_or_404(Category,slug = category_slug)
    products = Product.objects.filter(category = category,is_available =True)
    context = {"category": category,"products":products}
    return render(request,'store/product_list_by_category.html',context)
# get_object_or_404 только для конкретных объектов(товаров)

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Ваша корзина{% endblock %}

{% block content %}
<div class="container">
    <h1>Ваша корзина</h1>
    {% if cart|length > 0 %}
    <table class="cart-table">
        <thead>
            <tr>
                <th>Изображение</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена за шт.</th>
                <th>Общая цена</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}https://via.placeholder.com/80x80.png/dee2e6/6c757d?text=No+Image{% endif %}" class="cart-item-img">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td class="quantity">
                        <div style="display: flex; align-items: center; justify-content: center;">
                            <!-- Форма для кнопки "-" -->
                            <form action="{% url 'cart:cart_decrement' item.product.id %}" method="post" style="margin-right: 10px;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-secondary">-</button>
                            </form>
                            
                            <!-- Отображение количества -->
                            <span>{{ item.quantity }}</span>

                            <!-- Форма для кнопки "+" -->
                            <form action="{% url 'cart:cart_increment' item.product.id %}" method="post" style="margin-left: 10px;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-secondary">+</button>
                            </form>
                        </div>
                    </td>

                    <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="remove-btn">❌</button>
                        </form>
                    </td>
                    <td class="num">{{ item.price|floatformat:"0" }} ₽</td>
                    <td class="num">{{ item.total_price|floatformat:"0" }} ₽</td>
                </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td colspan="5">Итого</td>
                <td class="num">{{ cart.get_total_price|floatformat:"0" }} ₽</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'store:home' %}" class="btn btn-secondary">Продолжить покупки</a>
        <a href="#" class="btn btn-primary">Оформить заказ</a>
    </p>
    {% else %}
        <p>Ваша корзина пуста.</p>
        <a href="{% url 'store:home' %}" class="btn btn-primary">К покупкам</a>
    {% endif %}
</div>
{% endblock %}
 

orders/templates/order/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}Оформление заказа{% endblock %}

{% block content %}
<div class="container">
    <div class="checkout-layout">
        <div class="order-form-container">
            <h1>Оформление заказа</h1>
            <p>Пожалуйста, заполните форму ниже, чтобы разместить ваш заказ.</p>
            <form method="post" class="order-form">
                <div class="form-group">
                    <label for=""></label>
                        <div class="form-errors">
                            <p></p>
                        </div>
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Разместить заказ</button>
            </form>
        </div>

        <div class="order-summary">
            <h3>Ваш заказ</h3>
            <ul>
                <li class="summary-item">
                    <span class="summary-item-name"></span>
                    <span class="summary-item-price"> ₽</span>
                </li>
            </ul>
            <div class="summary-total">
                <span>Итого</span>
                <span class="total-price"> ₽</span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/order/success.html
{% extends "base.html" %}
{% load static %}

{% block title %}Спасибо за заказ{% endblock %}

{% block content %}
<div class="container">
    <div class="order-success-message">
        <h1>Спасибо!</h1>
        <p>Ваш заказ успешно оформлен. Номер вашего заказа: <strong></strong>.</p>
        <p>Мы отправили подтверждение на ваш email. В ближайшее время наш менеджер свяжется с вами для уточнения деталей доставки.</p>
        <a href="" class="btn btn-primary">Вернуться на главную</a>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Блок title будет заменяться на дочерних страницах -->
    <title>{% block title %}TechStore{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>

    <header class="site-header">
        <div class="container">
        <div class="logo"><a href="{% url 'store:home' %}" class="logo-link">TechStore</a></div>
            <nav class="main-nav">
                <ul>
                <li><a href="{% url 'store:home' %}">Главная</a></li>
                    <li><a href="{% url 'store:category_list' %}">Каталог</a></li>
                    <li><a href="#">О нас</a></li>
                    <li><a href="#">Контакты</a></li>
                </ul>
            </nav>
            <div class="header-actions">
                <input type="search" placeholder="Поиск...">
                <a href="{% url 'cart:cart_detail' %}" class="cart-icon">🛒<span class="cart-count">{{cart|length}}</span></a>
                <a href="#" class="login-btn">Войти</a>
            </div>
        </div>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>
    <footer class="site-footer">
        <div class="container">
            <p>&copy; 2024 TechStore. Все права защищены.</p>
        </div>
    </footer>
</body>
</html>
 

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}TechStore - Магазин Компьютерной Техники{% endblock %}

{% block content %}
        <section class="hero">
            <div class="container">
                <h1>Лучшая компьютерная техника</h1>
                <p>Современные комплектующие и периферия по лучшим ценам.</p>
                <a href="{% url 'store:category_list' %}" class="btn btn-primary">Перейти в каталог</a>
            </div>
        </section>

        <section class="featured-products">
            <div class="container">
                <h2>Популярные товары</h2>
                <div class="product-grid">
                    <!-- Начинаем цикл для отображения товаров из базы данных -->
                    {% for product in products %}
                        <div class="product-card">
                            <a href="{% url 'store:product_detail' product.slug %}" class="product-card-main-link">
                                {% if product.image %}
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                                {% else %}
                                    <img src="https://via.placeholder.com/300x200.png/dee2e6/6c757d?text=No+Image" alt="Нет изображения">
                                {% endif %}
                                <h3>{{ product.name }}</h3>
                            </a>
                                <!-- stringformat убирает .00 с цены, если она целая -->
                                <p class="price">{{ product.price|floatformat:"0" }} ₽</p>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="quantity" value="1">
                                    <button type="submit" class="btn btn-secondary">В корзину</button>
                                </form>
                        </div>
                    {% endfor %}
                    <!-- Конец цикла -->
                </div>
            </div>
        </section>
{% endblock %}
 

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{product.name}} - TechStore{% endblock %} 

    {% block content %}
        <section class="product-detail-section">
            <div class="container product-detail-container">
                <div class="product-image-gallery">
                        <img src="{{ product.image.url }}" alt="названия изображений">
                </div>
                <div class="product-info">
                    <h1>{{ product.name }}</h1>
                    <p class="product-detail-price">{{ product.price | stringformat:".0f" }} ₽</p>
                    <p class="stock-status">
                        {% if product.stock > 0 and product.is_available %}
                            <span class="in-stock">В наличии</span>
                        {% else %}    
                            <span class="out-of-stock">Нет в наличии</span>
                        {% endif %}
                        </p>
                    <div class="description">
                        <h3>Описание</h3>
                        <p>{{ product.description }}</p>
                    </div>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form }}
                        <button type="submit" class="btn btn-primary btn-lg">Добавить в корзину</button>
                    </form>
                </div>
            </div>
        </section>
    {% endblock %}

templates/store/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Каталог товаров{% endblock %} 
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Каталог товаров</h1>
        </div>

        <div class="category-grid">
            {% for category in categories %}
            <a href="{{ category.get_absolute_url }}" class="category-card">
                <!-- .url - адрес до картинки(определяется автоматически)(где находится эта картинка ссылка на картинку) -->
                <img src="{{ category.image.url }}" class = "category-card-img" alt="{{ category.name }}">
                <div class="category-card-body">
                    <h3>{{ category.name }}</h3>
                    <p class="product-count">Товаров: {{ category.product_count }} </p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/store/product_list_by_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Категории товаров:{{ category.name }}{% endblock %} 

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>{{category.name}}</h1>
        </div>

        <section class="category-products">
            {% if products %}
                <div class="product-grid">
                    {% for product in products %}
                        <div class="product-card">
                            <a href="{{ product.get_absolute_url }}" class="product-card-main-link">
                                <img src="{{ product.image.url }}" alt="">
                                <h3>{{  product.name }}</h3>
                            </a>
                            <p class="price">{{  product.price|stringformat:".0f" }}₽</p>
                            <button class="btn btn-secondary">В корзину</button>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p class="empty-category-message">В этой категории пока нет товаров.</p>
            {% endif %}
            </section>
    </div>
{% endblock %}